FROM python:3.11-slim-bookworm

WORKDIR /app

# Sadece script'i kopyala
COPY ./scripts/convert_model.py .

# Gerekli ortam değişkenlerini Dockerfile'ın kendisinden al
ARG MODEL_NAME
ARG COMPUTE_TYPE
ENV MODEL_NAME=${MODEL_NAME}
ENV COMPUTE_TYPE=${COMPUTE_TYPE}

# Tek görev: script'i çalıştır. Tüm mantık artık script'in içinde.
CMD ["python", "convert_model.py"]