FROM vllm/vllm-openai:latest

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# --- DÜZELTME: Protobuf versiyonunu manuel olarak yükseltiyoruz ---
RUN pip install --no-cache-dir --upgrade protobuf

COPY ./app ./app
COPY grpc_test_client.py .
COPY pyproject.toml .

EXPOSE 16060 16061 16062
ENTRYPOINT []
CMD ["python3", "-m", "app.runner"]