FROM python:3.11-slim-bookworm

WORKDIR /app

# Gerekli tüm ağır bağımlılıkları kur
RUN apt-get update && apt-get install -y --no-install-recommends git && \
    pip install --no-cache-dir \
        "torch" --extra-index-url https://download.pytorch.org/whl/cpu \
        "ctranslate2[transformers]>=4.0.0" \
        "huggingface-hub>=0.20.0" && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./scripts/convert_model.py .

# Bu konteyner çalıştığında, sadece convert_model.py script'ini çalıştıracak
CMD ["python", "convert_model.py"]